---
title: "QB_final_project_Lana_plots"
author: "Lana Bolin"
date: "2/22/2019"
output: html_document
---

# Setup

```{r, warning=F, message=F}
rm(list = ls())
require("vegan")
require("dplyr")
require("magrittr")
require("ggplot2")
```

Nativity codes are:   
0 = native to Indiana  
1 = native to the US  
2 = exotic  
3 = invasive  

Check how many of each nativity code we have using dplyr
```{r}
setwd("~/GitHub/QB19_IndependentProject/")
crawley.full <- read.csv("Crawley.csv")
sbs.factors <- read.csv("sbs_factors.csv", header = TRUE)

crawley.full %>%
  group_by(Nativity.Code) %>%
  summarize(grpcount = n())

# Those 8 empty ones are just empty rows at the bottom of the df. Let's get rid of those, as well as the two empty columns at the end
crawley.full <- crawley.full[-c(293:300), -c(24, 25)]
crawley.df <- crawley.full[, -c(1:3)]  # Get rid of non-incidence columns

# Make a new dataframe with Site, Mulch, and Litter, and Richness
Mulch <- as.factor(sbs.factors$MULCH)
Weediness <- as.factor(sbs.factors$WEEDINESS)
Litter <- sbs.factors$LITTER
Site <- c("Athenaeum", "Bauman.Park", "Center.for.Inquiry", "Chinqpin.Oak.Park", 
"Community.Caring...Sharing", "Cottage.Home", "Englewood", "Fletcher.Gateway", 
"Fletcher.Park", "Historic.Meridian.Park", "Jonathan.Jennings", 
"Lynhurst", "Merrill.Street", "Paramount.Charter", "Purpose.Park", 
"Ransom.Place", "Skiles.Test", "University.Park", "Westminster", 
"Willard.Park")

df <- data.frame(Site = Site, Mulch = Mulch, Litter = Litter, Weediness = Weediness, Richness = colSums(crawley.df))

# Function to calculate sd
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}


```


# Models & Plots

## Mulch
```{r}
# Here's my mulch data frame to use for my plot
df.mulch <- data_summary(df, varname = "Richness", 
                    groupnames = c("Mulch"))

df.mulch %>% ggplot(aes(x = Mulch, y = Richness)) + 
  geom_bar(stat="identity", color="black") +
  geom_errorbar(aes(ymin = Richness - sd, ymax = Richness + sd), width = .2,
                 position=position_dodge(.9)) +
  theme(text = element_text(size = 25, face = "bold")) +
  theme(axis.text = element_text(size = 15, face = "bold"))

mulch.aov <- aov(df$Richness ~ df$Mulch)
summary(mulch.aov)

```


## Weediness
```{r}
# Here's my weediness data frame to use for my plot
df.weediness <- data_summary(df, varname = "Richness", 
                    groupnames = c("Weediness"))

df.weediness %>% ggplot(aes(x = Weediness, y = Richness)) + 
  geom_bar(stat="identity", color="black") +
  geom_errorbar(aes(ymin = Richness - sd, ymax = Richness + sd), width = .2,
                 position=position_dodge(.9)) +
  theme(text = element_text(size = 25, face = "bold")) +
  theme(axis.text = element_text(size = 15, face = "bold"))

weediness.aov <- aov(df$Richness ~ df$Weediness)
summary(weediness.aov)
```


```{r}

```

